services:
  web:
    build:
      target: debug
    volumes:
      - ./web/code/:/home/happypaws/code/
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}
