services:
  web:
    restart: no
    volumes:
      - ./web/code:/home/happypaws/code
    command:
      - "sh"
      - "-c"
      - |
        python manage.py makemigrations adoptions animals medical_cases reports &&
        python manage.py makemigrations &&
        python manage.py migrate
