# Generated by Django 5.1.15 on 2026-05-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('tamano', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10, verbose_name='tamaño')),
                ('edad_aprox', models.CharField(blank=True, max_length=50, verbose_name='edad aproximada')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('rescatado', 'Rescatado'), ('en_tratamiento', 'En tratamiento'), ('en_adopcion', 'En adopción'), ('hogar_temporal', 'En hogar temporal'), ('adoptado', 'Adoptado')], default='rescatado', max_length=20)),
                ('esterilizado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
                ('foto_principal', models.ImageField(blank=True, upload_to='animales/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animales',
                'ordering': ['-fecha_ingreso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='animales/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('veterinario', models.CharField(blank=True, max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='animals.animal')),
            ],
            options={
                'verbose_name': 'registro médico',
                'verbose_name_plural': 'historial médico',
                'ordering': ['-fecha'],
            },
        ),
    ]
