# Generated by Django 5.1.15 on 2026-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_destacado_animal_fecha_esterilizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='barrio',
            field=models.CharField(blank=True, max_length=120, verbose_name='barrio / sector'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parroquia',
            field=models.CharField(blank=True, max_length=120, verbose_name='parroquia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor_contacto',
            field=models.CharField(blank=True, help_text='Opcional. Teléfono o correo del tutor o cuidador.', max_length=200, verbose_name='contacto del tutor (teléfono o correo)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre del tutor / responsable'),
        ),
    ]
