# Generated by Django 5.1.15 on 2026-07-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('cedula', models.CharField(max_length=20, verbose_name='cédula')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('otro', 'Otro')], max_length=15, verbose_name='tipo de vivienda')),
                ('tiene_patio', models.BooleanField(default=False, verbose_name='¿tiene patio o espacio exterior?')),
                ('experiencia', models.TextField(blank=True, verbose_name='experiencia previa con mascotas')),
                ('motivo', models.TextField(verbose_name='¿por qué quieres adoptar a este animal?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('notas_internas', models.TextField(blank=True, verbose_name='notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='animals.animal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_adopcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de adopción',
                'verbose_name_plural': 'solicitudes de adopción',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='adopciones/seguimiento/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='adoptions.adoptionapplication')),
            ],
            options={
                'verbose_name': 'seguimiento post-adopción',
                'verbose_name_plural': 'seguimientos post-adopción',
                'ordering': ['-fecha'],
            },
        ),
    ]
