# Generated by Django 5.1.15 on 2026-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='proposito',
            field=models.CharField(choices=[('compania', 'Compañía'), ('reproduccion', 'Reproducción'), ('guardian', 'Guardián'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='compania', max_length=15, verbose_name='¿para qué quieres a la mascota?'),
        ),
    ]
