# Generated by Django 5.1.15 on 2026-07-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('meta_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='meta de recaudación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=10)),
                ('foto', models.ImageField(blank=True, upload_to='casos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_medicos', to='animals.animal')),
            ],
            options={
                'verbose_name': 'caso médico',
                'verbose_name_plural': 'casos médicos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(max_length=200, verbose_name='nombre del donante')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.ImageField(blank=True, upload_to='casos/comprobantes/')),
                ('verificado', models.BooleanField(default=False, help_text='Marca la donación como verificada para sumarla al total recaudado.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='medical_cases.medicalcase')),
            ],
            options={
                'verbose_name': 'donación',
                'verbose_name_plural': 'donaciones',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='casos/avances/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='medical_cases.medicalcase')),
            ],
            options={
                'verbose_name': 'avance del caso',
                'verbose_name_plural': 'avances del caso',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
