# Generated by Django 5.2.16 on 2026-09-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0002_alter_donation_nombre_donante_casephoto_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcase',
            name='foto',
        ),
    ]
