# Generated by Django 5.1.15 on 2026-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_interaccion_comunitaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Solo los reportes aprobados se muestran al público (evita spam).', verbose_name='aprobado por el staff'),
        ),
        migrations.AddField(
            model_name='report',
            name='callejero',
            field=models.BooleanField(default=False, help_text='Marca si el animal parece no tener dueño (vive en la calle).', verbose_name='¿parece callejero / sin dueño?'),
        ),
        migrations.AddField(
            model_name='report',
            name='especie',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, verbose_name='especie'),
        ),
        migrations.AddField(
            model_name='report',
            name='hora_aproximada',
            field=models.TimeField(blank=True, help_text='Opcional. Si recuerdas más o menos a qué hora ocurrió.', null=True, verbose_name='hora aproximada del suceso'),
        ),
        migrations.AddField(
            model_name='report',
            name='senales_distinguibles',
            field=models.TextField(blank=True, help_text='Collar, tratamiento veterinario, cicatrices, manchas, etc.', verbose_name='señales distinguibles'),
        ),
        migrations.AddField(
            model_name='report',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'No estoy seguro/a')], max_length=12, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contacto_reportante',
            field=models.CharField(blank=True, help_text='Opcional. Déjalo si quieres que te contacten para dar seguimiento.', max_length=200, verbose_name='tu contacto (teléfono o correo)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre_reportante',
            field=models.CharField(blank=True, max_length=200, verbose_name='tu nombre'),
        ),
    ]
