# Generated by Django 5.1.15 on 2026-06-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='nombre_donante',
            field=models.CharField(blank=True, help_text='Déjalo en blanco para aparecer como donante anónimo.', max_length=200, verbose_name='nombre del donante'),
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='casos/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='medical_cases.medicalcase')),
            ],
            options={
                'verbose_name': 'foto del caso',
                'verbose_name_plural': 'fotos del caso',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('factura', 'Factura veterinaria'), ('rayos_x', 'Rayos X'), ('medicina', 'Medicina'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.ImageField(blank=True, upload_to='casos/egresos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='medical_cases.medicalcase')),
            ],
            options={
                'verbose_name': 'egreso',
                'verbose_name_plural': 'egresos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
