# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Solo los reportes aprobados se muestran al público (evita spam).', verbose_name='aprobado por el staff'),
        ),
        migrations.AddField(
            model_name='report',
            name='callejero',
            field=models.BooleanField(default=False, help_text='Marca si el animal parece no tener dueño (vive en la calle).', verbose_name='¿parece callejero / sin dueño?'),
        ),
        migrations.AddField(
            model_name='report',
            name='especie',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, verbose_name='especie'),
        ),
        migrations.AddField(
            model_name='report',
            name='hora_aproximada',
            field=models.TimeField(blank=True, help_text='Opcional. Si recuerdas más o menos a qué hora ocurrió.', null=True, verbose_name='hora aproximada del suceso'),
        ),
        migrations.AddField(
            model_name='report',
            name='senales_distinguibles',
            field=models.TextField(blank=True, help_text='Collar, tratamiento veterinario, cicatrices, manchas, etc.', verbose_name='señales distinguibles'),
        ),
        migrations.AddField(
            model_name='report',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'No estoy seguro/a')], max_length=12, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contacto_reportante',
            field=models.CharField(blank=True, help_text='Opcional. Déjalo si quieres que te contacten para dar seguimiento.', max_length=200, verbose_name='tu contacto (teléfono o correo)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre_reportante',
            field=models.CharField(blank=True, max_length=200, verbose_name='tu nombre'),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='tu nombre')),
                ('contacto', models.CharField(blank=True, help_text='Teléfono o correo, por si quieren responderte.', max_length=200, verbose_name='contacto (opcional)')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('oculto', models.BooleanField(default=False, verbose_name='oculto por moderación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='reports.report')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='ReportSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='tu nombre')),
                ('contacto', models.CharField(blank=True, help_text='Teléfono o correo, por si el dueño necesita más detalles.', max_length=200, verbose_name='contacto (opcional)')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='¿dónde lo viste?')),
                ('fecha', models.DateField(verbose_name='¿cuándo lo viste?')),
                ('descripcion', models.TextField(blank=True, verbose_name='detalles')),
                ('foto', models.ImageField(blank=True, upload_to='reportes/avistamientos/', verbose_name='foto (opcional)')),
                ('confirmado', models.BooleanField(default=False, verbose_name='confirmado por la fundación')),
                ('oculto', models.BooleanField(default=False, verbose_name='oculto por moderación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='reports.report')),
            ],
            options={
                'verbose_name': 'avistamiento',
                'verbose_name_plural': 'avistamientos',
                'ordering': ['-creado'],
            },
        ),
    ]
