# Generated by Django 5.2.16 on 2026-09-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_aprobado_report_callejero_report_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], max_length=12, verbose_name='sexo'),
        ),
    ]
