# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='barrio',
            field=models.CharField(blank=True, help_text='Ej. 24 de Mayo', max_length=120, verbose_name='barrio / sector'),
        ),
        migrations.AddField(
            model_name='animal',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Muéstralo al inicio del catálogo (perro en situación vulnerable).', verbose_name='destacar como vulnerable'),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_esterilizacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de esterilización'),
        ),
        migrations.AddField(
            model_name='animal',
            name='origen',
            field=models.CharField(choices=[('domestico', 'Doméstico (nació en una casa)'), ('rescatado', 'Rescatado (nació en la calle)'), ('comunitario', 'Comunitario (vive en la calle)')], default='rescatado', max_length=15, verbose_name='origen del animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parroquia',
            field=models.CharField(blank=True, max_length=120, verbose_name='parroquia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor_contacto',
            field=models.CharField(blank=True, help_text='Opcional. Teléfono o correo del tutor o cuidador.', max_length=200, verbose_name='contacto del tutor (teléfono o correo)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre del tutor / responsable'),
        ),
    ]
