[uwsgi]
socket=/home/happypaws/code/uwsgi/uwsgi_app.sock
http-socket = 127.0.0.1:9090
chdir = /home/happypaws/code
module=happypaws.wsgi:application
master=true
chmod-socket=666
# Usa las credenciales del usuario creado
uid=1001
gid=1001
vacuum=true
# En SIGTERM, termina como cuando se envia una señal para detener contenedor
die-on-term = true 
