[uwsgi]
socket=/home/happypaws/code/uwsgi/uwsgi_app.sock
chdir = /home/happypaws/code
module=happypaws.wsgi:application
master=true
chmod-socket=666
# TODO: Usar usuario no-root ocmo www-data 
uid=root
gid=root
vacuum=true
